# Server Configuration
server:
  port: 8080
  host: "127.0.0.1"
  sizelimit: 131072000 # 125MB

# Logging Configuration
logger:
  logfilepath: "/data/ghproxy/log/ghproxy.log"
  maxlogsize: 5 # MB

# CORS Configuration
cors:
  enabled: true

# Authentication Configuration
auth:
  enabled: false
  authtoken: "test"

# Blacklist Configuration
blacklist:
  enabled: false
  blacklistfile: "/data/ghproxy/config/blacklist.json"

# Whitelist Configuration
whitelist:
  enabled: false
  whitelistfile: "/data/ghproxy/config/whitelist.json"